/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorestaurante;

import RestauranteApp.Comidas;
import RestauranteApp.Menus;
import RestauranteApp.ServicioExpres;
import RestauranteApp.global;
import RestauranteApp.saloneros;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.Metodos;
import static RestauranteApp.global.Express;
import static RestauranteApp.global.descuent;
import static RestauranteApp.global.Total;
/**
 *
 * @author 
 */
public class Factura extends javax.swing.JFrame {
    
     ArrayList<saloneros> listaSaloneros = new ArrayList();
     ArrayList<ServicioExpres> listaExpres = new ArrayList();
     Menus menus = new Menus();
     Metodos metodos = new Metodos();
     DefaultTableModel mdlTabla;
     Vector vCabeceras = new Vector();

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
 
        mess.setText(menus.getNmesa());
        
        vCabeceras.addElement("Mesa");
        vCabeceras.addElement("Nombre");
        vCabeceras.addElement("Precio");
        vCabeceras.addElement("Cantidad");
        mdlTabla = new DefaultTableModel(vCabeceras,0);
        jTable1.setModel(mdlTabla);
        
    }

    
     public void cargarItems(ArrayList<saloneros> listaSaloneros,ArrayList<ServicioExpres> listaExpres){
        this.listaSaloneros = listaSaloneros;
        this.listaExpres=listaExpres;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cedu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        descuento = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dirr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        mess = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Facturar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        iva = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        Pedido = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ced = new javax.swing.JTextField();
        BusqCedula = new javax.swing.JButton();
        des = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Factura");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 671, 38));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel2.setToolTipText("Cliente");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Nombre  Cliente:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 20));

        Name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 220, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Cédula:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, 20));

        cedu.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(cedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 220, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Télefono:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 60, 20));

        celular.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 220, 20));

        descuento.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel2.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 90, 20));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setText("Dirección:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));
        jPanel2.add(dirr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 220, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 350, 140));

        jLabel6.setText("Fecha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 255, 50, 20));

        jTable1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 670, 140));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mesa:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 40, 20));
        getContentPane().add(mess, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, 20));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 90, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Atendido Por:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 90, 20));

        lblCliente.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 240, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Horario de Atención:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 130, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Lunes a Viernes 8:00 am a 9:00pm");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 220, 20));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Sábados y Domingos 9:00am a 8:00pm");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 220, -1));

        Salir.setText("Salir ");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 150, 40));

        Facturar.setText("Facturar");
        Facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturarActionPerformed(evt);
            }
        });
        getContentPane().add(Facturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 130, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Iva:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 30, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total de Compra:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        iva.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        iva.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 100, 20));

        total.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 100, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SubTotal:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 60, 20));

        sub.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 100, 20));

        Pedido.setBackground(new java.awt.Color(0, 0, 0));
        Pedido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Pedido.setForeground(new java.awt.Color(255, 255, 255));
        Pedido.setText("Mostrar Pedido");
        Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoActionPerformed(evt);
            }
        });
        getContentPane().add(Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, -1));

        Eliminar.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar Pedido");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 130, -1));
        getContentPane().add(ced, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 89, 130, 20));

        BusqCedula.setText("Buscar");
        BusqCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusqCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(BusqCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 20));

        des.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 100, 20));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Express Cédula:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 20));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Descuento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 70, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, 260));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/restas.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 410, 240));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 280, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        MenuPrincipal men = new MenuPrincipal(){  
        };
         
         men.setLocationRelativeTo(null);
         men.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        for (saloneros c : listaSaloneros) {
            if (c.getNumeromesa().equals(mess.getText())) {
                lblCliente.setText("Salonero: " + c.getNombre());
                break;
            }
        }
        
        jTable1.setModel(metodos.listaMenu());
        //Muestra los valores del resultado de la compra
        sub.setText(String.valueOf(global.getSubTotal()));
        iva.setText(String.valueOf(global.getIva()));
        des.setText("0");
        total.setText(String.valueOf(global.getTotal()));
        
        if (Express.equals("1")) {
         double sub = global.getSubTotal();
         double iv = global.getIva();
         descuent = sub * 0.05;  
         double temmp = sub - descuent;
         des.setText(""+descuent);
         Total = temmp + iv;
         total.setText(""+Total);
         Express = "0";
         
        }

        
    }//GEN-LAST:event_buscarActionPerformed

    private void FacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturarActionPerformed
       
           int a=JOptionPane.showConfirmDialog(null,"Desea hacer la Factura Compartida?");  
           if(a==JOptionPane.YES_OPTION){
               String opcion = "Yes";
            do{
                String pago = JOptionPane.showInputDialog("Ingrese la Cantidad a Pagar?");
                double convertir = Integer.parseInt(pago);
                double NTotal = Total - convertir;
               if (NTotal == 0) {
                JOptionPane.showMessageDialog(null,"Pago Total realizado con éxito\n"
                        + "Factura Cancelada");
                opcion = "No";
               }else{
                   Total = NTotal;
                  JOptionPane.showMessageDialog(null,"Aún se debe cancelar: \n"
                          + "₡"+NTotal); 
                  opcion = "yes";
               }
            }while(opcion.equals("yes"));  
               dispose();
           }else{
              JOptionPane.showMessageDialog(null,"Total de Factura a Cancelar es de \n"
                      + "₡"+Total); 
              JOptionPane.showMessageDialog(null,"Factura Guardada con Éxito");
              dispose();
           }
                  
    }//GEN-LAST:event_FacturarActionPerformed

    private void PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoActionPerformed
        jTable1.setModel(metodos.listaMenu());
    }//GEN-LAST:event_PedidoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
     String Path = "Menu.txt";
        try{
          metodos.borrarArchivo(Path);
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error"+e);
        }   
    }//GEN-LAST:event_EliminarActionPerformed

    private void BusqCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusqCedulaActionPerformed
        for (ServicioExpres c : listaExpres) {
            if (c.getCedula().equals(ced.getText())) {
                Name.setText(c.getNombre());
                cedu.setText(c.getCedula());
                celular.setText(c.getTelefono());
                dirr.setText(c.getDireccion());
                break;
            }
        }
    }//GEN-LAST:event_BusqCedulaActionPerformed

    public ArrayList<saloneros> nuevo() {
        return listaSaloneros;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusqCedula;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Facturar;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Pedido;
    private javax.swing.JButton Salir;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField ced;
    private javax.swing.JTextField cedu;
    private javax.swing.JTextField celular;
    private javax.swing.JLabel des;
    private javax.swing.JLabel descuento;
    private javax.swing.JTextField dirr;
    private javax.swing.JLabel iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JTextField mess;
    private javax.swing.JLabel sub;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
