/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorestaurante;

import RestauranteApp.Comidas;
import RestauranteApp.Mesa;
import RestauranteApp.ServicioExpres;
import RestauranteApp.saloneros;
import java.util.ArrayList;
import javax.swing.JFrame;
import static RestauranteApp.global.Express;

/**
 *
 * @author 
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    public ArrayList<Mesa> listaMesa = new ArrayList();
    public ArrayList<saloneros> listaSaloneros = new ArrayList();
    public ArrayList<Comidas> listaComidas = new ArrayList();
    public ArrayList<ServicioExpres> listaExpres = new ArrayList();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    //Retorna Jframe anterior
    private JFrame getFrame() {
        return this;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Factura = new javax.swing.JButton();
        Mesas = new javax.swing.JButton();
        Saloneros = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        Platillos = new javax.swing.JButton();
        Expres = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 405));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú de Opciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 30));

        Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facc.png"))); // NOI18N
        Factura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        Factura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FacturaMouseMoved(evt);
            }
        });
        Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaActionPerformed(evt);
            }
        });
        getContentPane().add(Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 130, 150));

        Mesas.setBackground(new java.awt.Color(0, 0, 204));
        Mesas.setForeground(new java.awt.Color(0, 0, 102));
        Mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesass.jpg"))); // NOI18N
        Mesas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Mesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N
        Mesas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MesasMouseMoved(evt);
            }
        });
        Mesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesasActionPerformed(evt);
            }
        });
        getContentPane().add(Mesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 150));

        Saloneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salon.png"))); // NOI18N
        Saloneros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Saloneros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        Saloneros.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SalonerosMouseMoved(evt);
            }
        });
        Saloneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalonerosActionPerformed(evt);
            }
        });
        getContentPane().add(Saloneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 120, 150));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menus.jpg"))); // NOI18N
        Menu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Comidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        Menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MenuMouseMoved(evt);
            }
        });
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 120, 150));

        Platillos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plat.jpg"))); // NOI18N
        Platillos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Platillos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        Platillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatillosActionPerformed(evt);
            }
        });
        getContentPane().add(Platillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 150));

        Expres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/express.jpg"))); // NOI18N
        Expres.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedidos Express", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        Expres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpresActionPerformed(evt);
            }
        });
        getContentPane().add(Expres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 120, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lujoso.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 620, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void SalonerosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalonerosMouseMoved
       Saloneros.setToolTipText("*INGRESAR SALONEROS"); 
    }//GEN-LAST:event_SalonerosMouseMoved

    private void MesasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MesasMouseMoved
        Mesas.setToolTipText("*INGRESAR MESAS");
    }//GEN-LAST:event_MesasMouseMoved

    private void MenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseMoved
       Menu.setToolTipText("*VER MENÚ");
    }//GEN-LAST:event_MenuMouseMoved

    private void FacturaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseMoved
       Factura.setToolTipText("*VER FACTURA");
    }//GEN-LAST:event_FacturaMouseMoved

    private void MesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesasActionPerformed
         IngMesa mes = new IngMesa(){
           @Override 
           public void dispose() {
                listaMesa = nuevo();
                getFrame().setVisible(true);
                super.dispose();
            }
           
        };
         mes.cargarDatos(listaMesa);
         mes.setLocationRelativeTo(null);
         mes.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_MesasActionPerformed

    private void SalonerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalonerosActionPerformed
        Salonero salo= new Salonero(){
            @Override  
             public void dispose() {
                listaSaloneros = nuevo();
                getFrame().setVisible(true);
                super.dispose();
            }
                
            };
            salo.cargarItems(listaMesa, listaSaloneros);
            salo.setLocationRelativeTo(null);
            salo.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_SalonerosActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        Menu menu = new Menu(){
           @Override 
           public void dispose() {
                listaComidas = nuevo();
                getFrame().setVisible(true);
                super.dispose();
            }
           
        };
         menu.cargarDatos(listaComidas);
         menu.setLocationRelativeTo(null);
         menu.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaActionPerformed
        Factura fac = new Factura(){
           @Override 
           public void dispose() { 
               listaSaloneros = nuevo();
                getFrame().setVisible(true);
                super.dispose();
            }
     
        };
         
         fac.cargarItems(listaSaloneros,listaExpres);
         fac.setLocationRelativeTo(null);
         fac.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_FacturaActionPerformed

    private void PlatillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatillosActionPerformed
        IngComidas comida = new IngComidas(){
           @Override 
           public void dispose() {
                listaComidas = nuevo();
                getFrame().setVisible(true);
                super.dispose();
            }
           
        };
         comida.cargarDatos(listaComidas);
         comida.setLocationRelativeTo(null);
         comida.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_PlatillosActionPerformed

    private void ExpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpresActionPerformed
        Express = "1";
        
         Express exp = new Express(){
           @Override 
           public void dispose() { 
               listaExpres = nuevo();
                getFrame().setVisible(true);
                super.dispose();
            }
     
        };
         
         exp.cargarDatos(listaExpres);
         exp.setLocationRelativeTo(null);
         exp.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_ExpresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Expres;
    private javax.swing.JButton Factura;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Mesas;
    private javax.swing.JButton Platillos;
    private javax.swing.JButton Saloneros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
