/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorestaurante;

import RestauranteApp.Comidas;
import RestauranteApp.Menus;
import static RestauranteApp.global.prec;
import static RestauranteApp.global.Cpre;
import static RestauranteApp.global.pnuevo;
import static RestauranteApp.global.ppost;
import static RestauranteApp.global.subTotal;
import static RestauranteApp.global.iva;
import static RestauranteApp.global.Total;
import static RestauranteApp.global.nuev;
import static RestauranteApp.global.nuev1;
import static RestauranteApp.global.nuev2;
import static RestauranteApp.global.nuev3;
import RestauranteApp.saloneros;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import metodos.Metodos;

/**
 *
 * @author 
 */
public class Menu extends javax.swing.JFrame {

    Menus menus = new Menus();
    Metodos metodos = new Metodos();
    
    
    ArrayList<Comidas> listaComidas = new ArrayList();
    ArrayList<saloneros> listaSaloneros = new ArrayList();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    
    public void cargarDatos(ArrayList<Comidas> listaComidas) {
        this.listaComidas = listaComidas;
        listaComidas.forEach((d) -> {
            nuevos.addItem(d.getNombreComida());
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        Bebida = new javax.swing.JComboBox<>();
        ico = new javax.swing.JLabel();
        beb = new javax.swing.JSpinner();
        precio = new javax.swing.JLabel();
        Entrada = new javax.swing.JComboBox<>();
        eprecio = new javax.swing.JLabel();
        Entradac = new javax.swing.JSpinner();
        platillos = new javax.swing.JLabel();
        Postre = new javax.swing.JComboBox<>();
        postr = new javax.swing.JSpinner();
        nuevos = new javax.swing.JComboBox<>();
        Ncant = new javax.swing.JSpinner();
        postres = new javax.swing.JLabel();
        ppre = new javax.swing.JLabel();
        Nuepre = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MENU RESTAURANTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 7, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 760, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MM.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 500));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Entradas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bebidas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 50, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nuevos Platillos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 100, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Postres");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, 30));

        Regresar.setBackground(new java.awt.Color(153, 153, 0));
        Regresar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Regresar.setForeground(new java.awt.Color(0, 0, 0));
        Regresar.setText("Ir  A Facturar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 150, 40));

        Bebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca Cola", "Fanta Naranja", "Gin", "Cerveza", "wisky", "Agua Voss", " " }));
        Bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidaActionPerformed(evt);
            }
        });
        getContentPane().add(Bebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 140, 30));

        ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coca.jpg"))); // NOI18N
        getContentPane().add(ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 180, 180));
        getContentPane().add(beb, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 50, 30));

        precio.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 230, 20));

        Entrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alitas de Pollo", "Ceviche", "Empanadas de Pollo", "Casado", "Gallo Pinto", "Olla de Carne", "Tamal de Cerdo", "Chifrijo", "Chicharrones" }));
        Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaActionPerformed(evt);
            }
        });
        getContentPane().add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 130, 30));

        eprecio.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(eprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 190, 20));
        getContentPane().add(Entradac, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 50, 30));

        platillos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alitas.jpg"))); // NOI18N
        getContentPane().add(platillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 260, 160));

        Postre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romina Cardenas", "Tarta de Chocolate", "Crepe", "Tres Leches", "Beijinhos" }));
        Postre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostreActionPerformed(evt);
            }
        });
        getContentPane().add(Postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 140, 30));
        getContentPane().add(postr, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 40, 30));

        nuevos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sopa de Pollo" }));
        nuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevosActionPerformed(evt);
            }
        });
        getContentPane().add(nuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 150, 30));
        getContentPane().add(Ncant, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 40, 30));

        postres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/romina.jpg"))); // NOI18N
        getContentPane().add(postres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 260, 130));

        ppre.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(ppre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, 20));

        Nuepre.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(Nuepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 375, 160, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 120, 30));

        Guardar.setBackground(new java.awt.Color(51, 0, 0));
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar Orden");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 160, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rest.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 610, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidaActionPerformed
       
         if (Bebida.getSelectedItem()=="Coca Cola") {
            String icon = "/img/coca.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            ico.setIcon(icono);
            precio.setText("Precio = ₡ 1800");
           prec = 1800;
        } else if (Bebida.getSelectedItem()=="Fanta Naranja") {
            String icon = "/img/fantanara.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            ico.setIcon(icono);
            precio.setText("Precio = ₡1800");
            prec = 1800;
        }else if(Bebida.getSelectedItem()=="Gin"){
           String icon = "/img/gin.png";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            ico.setIcon(icono); 
            precio.setText("Precio = ₡1800");
            prec = 1800;
        } else if(Bebida.getSelectedItem()=="Cerveza"){
           String icon = "/img/cerveza.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            ico.setIcon(icono); 
            precio.setText("Precio = ₡2000");
            prec = 2000;
        } else if(Bebida.getSelectedItem()=="wisky"){
           String icon = "/img/wisky.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            ico.setIcon(icono);  
            precio.setText("Precio = ₡2800");
            prec = 2800;
        } else if(Bebida.getSelectedItem()=="Agua Voss"){
            String icon = "/img/voss.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            ico.setIcon(icono);
            precio.setText("Precio = ₡1500");
            prec = 1500;
        }
           
    }//GEN-LAST:event_BebidaActionPerformed

    private void EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaActionPerformed
    
        if (Entrada.getSelectedItem()=="Alitas de Pollo") {
            String icon = "/img/alitas.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono);
            eprecio.setText("Precio = ₡4500");
            Cpre = 4500;
        } else if (Entrada.getSelectedItem()=="Ceviche") {
            String icon = "/img/ceviche.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono);
            eprecio.setText("Precio = ₡2500");
            Cpre = 2500;
        }else if(Entrada.getSelectedItem()=="Empanadas de Pollo"){
           String icon = "/img/empanadas.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono); 
           eprecio.setText("Precio = ₡1000");
           Cpre = 1000;
        } else if(Entrada.getSelectedItem()=="Casado"){
           String icon = "/img/casado.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono);
            eprecio.setText("Precio = ₡3500");
            Cpre = 3500;
        } else if(Entrada.getSelectedItem()=="Gallo Pinto"){
           String icon = "/img/pinto.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono); 
            eprecio.setText("Precio = ₡2800");
            Cpre = 2800;
        } else if(Entrada.getSelectedItem()=="Olla de Carne"){
            String icon = "/img/olla.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono);
            eprecio.setText("Precio = ₡2500");
            Cpre = 2500;
        }else if(Entrada.getSelectedItem()=="Tamal de Cerdo"){
            String icon = "/img/tamal.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono);
            eprecio.setText("Precio = ₡800");
            Cpre = 800;
        }else if(Entrada.getSelectedItem()=="Chifrijo"){
            String icon = "/img/chifri.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono);
            eprecio.setText("Precio = ₡2900");
            Cpre = 2900;
        }else if(Entrada.getSelectedItem()=="Chicharrones"){
            String icon = "/img/chi.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            platillos.setIcon(icono);
            eprecio.setText("Precio = ₡2500");
            Cpre = 2500;
        }
       
       
    }//GEN-LAST:event_EntradaActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
      
        MenuPrincipal men = new MenuPrincipal(){  
        };
         
         men.setLocationRelativeTo(null);
         men.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void PostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostreActionPerformed
        //Postres
      
         if (Postre.getSelectedItem()=="Romina Cardenas") {
            String icon = "/img/romina.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            postres.setIcon(icono);
            ppre.setText("Precio = ₡3500");
            ppost = 3500;
        } else if (Postre.getSelectedItem()=="Tarta de Chocolate") {
            String icon = "/img/tarta.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            postres.setIcon(icono);
            ppre.setText("Precio = ₡4500");
            ppost = 4500;
        }else if(Postre.getSelectedItem()=="Crepe"){
           String icon = "/img/crepe.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            postres.setIcon(icono); 
           ppre.setText("Precio = ₡2000");
           ppost = 2000;
        } else if(Postre.getSelectedItem()=="Tres Leches"){
           String icon = "/img/tres.jpg";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            postres.setIcon(icono);
            ppre.setText("Precio = ₡3500");
            ppost = 3500;
        } else if(Postre.getSelectedItem()=="Beijinhos"){
           String icon = "/img/beijinho.png";
            URL url = this.getClass().getResource(icon);
            ImageIcon icono = new ImageIcon(url);
            postres.setIcon(icono); 
           ppre.setText("Precio = ₡1000");
            ppost = 1000;
        } 
    }//GEN-LAST:event_PostreActionPerformed

    private void nuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevosActionPerformed
       String temp = "";
        for(Comidas d : listaComidas){
            if (d.getNombreComida().equals(nuevos.getSelectedItem().toString())) {
                temp = d.getNombreComida();
                pnuevo = Integer.parseInt(d.getPrecioComida());
                Nuepre.setText("Precio = ₡"+pnuevo);
            }else if(nuevos.getSelectedItem()=="Sopa de Pollo"){
                pnuevo = 3000;
                Nuepre.setText("Precio = ₡"+pnuevo);
            }
        }
    }//GEN-LAST:event_nuevosActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
         // Facturar
        
        String Entradas = "",Entradacant= "",Bebidas= "",Bebidacant= "",nmesa= "",Poss = "",Postrecant = "",Nuev = "",CNuev= "";
        int Bebidasprecio = 0,Entradasprecio= 0,Postreprecio= 0,Nprecio= 0;
       nmesa = JOptionPane.showInputDialog("Ingrese el Número de Mesa");
       
       Entradas = Entrada.getSelectedItem().toString();
       Entradasprecio = Cpre;
       Entradacant = Entradac.getValue().toString();
       
       Bebidas = Bebida.getSelectedItem().toString();
       Bebidasprecio = prec;
       Bebidacant = beb.getValue().toString();
       
       Poss = Postre.getSelectedItem().toString();
       Postreprecio = ppost;
       Postrecant = postr.getValue().toString();
       
       Nuev = nuevos.getSelectedItem().toString();
       Nprecio = pnuevo;
       CNuev = Ncant.getValue().toString();
       
       //convertir los valores cantidades de String a int
        nuev = Integer.parseInt(Entradacant);
        nuev1 = Integer.parseInt(Bebidacant);
        nuev2 = Integer.parseInt(Postrecant);
        nuev3 = Integer.parseInt(CNuev);
       //Verificar si en los demás hay pedido sino poner valores en 0
        if (Entradacant.equals("0")) {
            Entradas = "";
            Entradasprecio = 0;
            nuev = 0;
        }
        
        if (Bebidacant.equals("0")) {
            Bebidas= "";
            Bebidasprecio = 0;
            nuev1 = 0;
        }
        
        if (Postrecant.equals("0")) {
          Poss = "";
          Postreprecio = 0;
          nuev2 = 0;
        }
        
        if (CNuev.equals("0")) {
            Nuev = "";
            Nprecio = 0;
            nuev3 = 0;
        }
        
        subTotal = (Entradasprecio * nuev) + (Bebidasprecio * nuev1 )+ (Postreprecio * nuev2) + (Nprecio * nuev3);
        iva = subTotal * 0.13;
        Total = subTotal + iva;
       JOptionPane.showMessageDialog(null,
         "Platillo : "+Entradas+" Precio: "+Entradasprecio + " Cantidad Pedida: "+Entradacant+
         " \nBebida : "+Bebidas+" Precio: "+Bebidasprecio + " Cantidad Pedida: "+Bebidacant+  
         " \nPostres : "+Poss+" Precio: "+Postreprecio + " Cantidad Pedida: "+Postrecant+
         " \nNuevo Platillo: "+Nuev+" Precio: "+Nprecio + " Cantidad Pedida: "+CNuev+
                 "\n"+
                 "\nSe Guardado Con Exito");
        
        //Enviar para guardar 
        
        menus.setNmesa(nmesa);
        menus.setEntrada(Entradas);
        menus.setPentrada(Entradasprecio);
        menus.setCentrada(Entradacant);
        
        menus.setNmesa(nmesa);
        menus.setBebida(Bebidas);
        menus.setPbebida(Bebidasprecio);
        menus.setCbebida(Bebidacant);
        
        menus.setNmesa(nmesa);
        menus.setPostre(Poss);
        menus.setPpostres(Postreprecio);
        menus.setCpostres(Postrecant);
        
        menus.setNmesa(nmesa);
        menus.setNuevos(Nuev);
        menus.setPnuevos(Nprecio);
        menus.setCnuevos(CNuev);
        metodos.Guardar(menus);
        metodos.GuardarArchivo(menus); 
      
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public ArrayList<Comidas> nuevo() {
        return listaComidas;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bebida;
    private javax.swing.JComboBox<String> Entrada;
    private javax.swing.JSpinner Entradac;
    private javax.swing.JButton Guardar;
    private javax.swing.JSpinner Ncant;
    private javax.swing.JLabel Nuepre;
    private javax.swing.JComboBox<String> Postre;
    private javax.swing.JButton Regresar;
    private javax.swing.JSpinner beb;
    private javax.swing.JLabel eprecio;
    private javax.swing.JLabel ico;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> nuevos;
    private javax.swing.JLabel platillos;
    private javax.swing.JSpinner postr;
    private javax.swing.JLabel postres;
    private javax.swing.JLabel ppre;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
}
